name: PR Deploy

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  deploy:
    name: Deploy PR env
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request' && !github.event.workflow_run.head_repository.fork && secrets.PR_DEPLOY_HOST != '' && secrets.PR_DEPLOY_SSH_KEY != '' }}
    permissions:
      contents: read
    concurrency:
      group: pr-deploy-${{ github.event.workflow_run.pull_requests[0].number }}
      cancel-in-progress: true
    env:
      PR_NUMBER: ${{ github.event.workflow_run.pull_requests[0].number }}
      DEPLOY_HOST: ${{ secrets.PR_DEPLOY_HOST }}
      DEPLOY_USER: deploy
    steps:
      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Load SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PR_DEPLOY_SSH_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts

      - name: Verify SSH connectivity
        run: |
          ssh -o BatchMode=yes "$DEPLOY_USER@$DEPLOY_HOST" "echo 'SSH connection OK'"

      - name: Deploy PR to remote
        run: |
          bash deploy/deploy.sh -HostName "$DEPLOY_HOST" -User "$DEPLOY_USER" -Version "PR-$PR_NUMBER"


